#!/usr/bin/env bash
# looping bad luck for a chance
i=0

while ((i < 10))
do 
	((i++))
	if ((i == 4))
	then 
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
