#!/usr/bin/env bash
# this script will give info about the file school
FILE="school"

if [[ -e $FILE ]]
	then 
		echo "school file exist"

		if [[ -s $FILE ]]
			then
				echo "school file is not empty"
		else 
			echo "school file is empty"
		fi

		if [[ -f  $FILE ]] 
			then
				echo "school is a regular file"

		fi

else 
	echo "school file doesn't exist"
fi
