#!/usr/bin/env bash
# this script will give info about the file school
FILE="school"

if [[ -e $FILE ]]
	then 
		echo "School file exist"

		if [[ -s $FILE ]]
			then
				echo "School file is not empty"
		else 
			echo "School file is empty"
		fi

		if [[ -f  $FILE ]] 
			then
				echo "School is a regular file"

		fi

else 
	echo "School file doesn't exist"
fi
